"""Your migration message

Revision ID: 33d40b8c04e2
Revises: 7ffd01e7be0e
Create Date: 2024-05-04 14:17:36.131687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d40b8c04e2'
down_revision = '7ffd01e7be0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_N', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_name')
    # ### end Alembic commands ###
