"""Your migration message

Revision ID: 7ffd01e7be0e
Revises: 
Create Date: 2024-05-04 08:22:21.435989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffd01e7be0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_end_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('scheduled_end_time')
        batch_op.drop_column('scheduled_start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('scheduled_end_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('scheduled_end_date')
        batch_op.drop_column('scheduled_start_date')

    # ### end Alembic commands ###
