"""Description of the changes

Revision ID: e4586eb850fd
Revises: 07f17fe20359
Create Date: 2025-02-11 14:40:03.509265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4586eb850fd'
down_revision = '07f17fe20359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('time_in',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('time_out',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('time_out',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('time_in',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
