"""Your migration message

Revision ID: f06fbb7d7168
Revises: 33d40b8c04e2
Create Date: 2025-01-18 17:49:38.143764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06fbb7d7168'
down_revision = '33d40b8c04e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('time_in',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('time_out')
        batch_op.drop_column('date_attended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_attended', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('time_out', sa.TIME(), nullable=False))
        batch_op.alter_column('time_in',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
